version: '3.8'

services:
  geotech-qa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geotech-qa-service-dev
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - LOG_LEVEL=DEBUG
      - MAX_QUESTION_LENGTH=2000
      - LLM_TIMEOUT_SECONDS=15.0
    volumes:
      # Mount source code for hot reload
      - ./app:/app/app
      - ./static:/app/static
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - geotech-network

networks:
  geotech-network:
    driver: bridge
