version: '3.8'

services:
  geotech-qa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geotech-qa-service
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - LOG_LEVEL=INFO
      - MAX_QUESTION_LENGTH=2000
      - LLM_TIMEOUT_SECONDS=5.0
    volumes:
      # Mount logs directory for persistence
      - ./logs:/app/logs
      # Mount data directory for vector store persistence
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - geotech-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: geotech-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - geotech-qa
    restart: unless-stopped
    networks:
      - geotech-network
    profiles:
      - production

  # Optional: Add Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: geotech-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    depends_on:
      - geotech-qa
    restart: unless-stopped
    networks:
      - geotech-network
    profiles:
      - monitoring

  # Optional: Add Grafana for metrics visualization
  grafana:
    image: grafana/grafana:latest
    container_name: geotech-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - geotech-network
    profiles:
      - monitoring

networks:
  geotech-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
